import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


// import 'leaflet/dist/leaflet.css';
import 'leaflet/dist/leaflet.css'

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="flex min-h-screen" 
            style={{
              backgroundImage: "url('https://cityphotoscity.s3.eu-west-1.amazonaws.com/images/dublin/dublin29.jpg')",
              backgroundAttachment: 'fixed', // enables parallax
              backgroundPosition: 'center',
              backgroundRepeat: 'no-repeat',
              backgroundSize: 'cover',
            }}
          >
            <AppSidebar className="hidden md:block w-64 pt-[64px]"/>
            <div className="flex-1 p-4">
              <SidebarTrigger />
              {children}
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
