import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { MenuBar } from "@/components/MenuBar";
import { Providers } from "@/components/Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


// import 'leaflet/dist/leaflet.css';
import 'leaflet/dist/leaflet.css'

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App 1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <MenuBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
