export const neighborhoodsList = [
    'Bolton District',
    'Bury District',
    'Ancoats and Clayton',
    'Ardwick',
    'Baguley',
    'Bradford',
    'Brooklands',
    'Burnage',
    'Charlestown',
    'Cheetham',
    'Chorlton',
    'Chorlton Park',
    'City Centre',
    'Crumpsall',
    'Didsbury East',
    'Didsbury West',
    'Fallowfield',
    'Gorton North',
    'Gorton South',
    'Harpurhey',
    'Higher Blackley',
    'Hulme',
    'Levenshulme',
    'Longsight',
    'Miles Platting and Newton Heath',
    'Moss Side',
    'Moston',
    'Northenden',
    'Old Moat',
    'Rusholme',
    'Sharston',
    'Whalley Range',
    'Withington',
    'Woodhouse Park',
    'Oldham District',
    'Rochdale District',
    'Salford District',
    'Stockport District',
    'Tameside District',
    'Trafford District',
    'Wigan District',
];