export const neighborhoodsList = [
    "Allerton",
    "Baychester",
    "Belmont",
    "Bronxdale",
    "Castle Hill",
    "City Island",
    "Claremont Village",
    "Clason Point",
    "Concourse",
    "Concourse Village",
    "Co-op City",
    "Country Club",
    "Eastchester",
    "East Morrisania",
    "Edenwald",
    "Fieldston",
    "Fordham",
    "Highbridge",
    "Hunts Point",
    "Kingsbridge",
    "Longwood",
    "Melrose",
    "Morrisania",
    "Morris Heights",
    "Morris Park",
    "Mott Haven",
    "Mount Eden",
    "Mount Hope",
    "North Riverdale",
    "Norwood",
    "Olinville",
    "Parkchester",
    "Pelham Bay",
    "Pelham Gardens",
    "Port Morris",
    "Riverdale",
    "Schuylerville",
    "Soundview",
    "Spuyten Duyvil",
    "Throgs Neck",
    "Tremont",
    "Unionport",
    "University Heights",
    "Van Nest",
    "Wakefield",
    "Westchester Square",
    "West Farms",
    "Williamsbridge",
    "Woodlawn",
    "Bath Beach",
    "Bay Ridge",
    "Bedford-Stuyvesant",
    "Bensonhurst",
    "Bergen Beach",
    "Boerum Hill",
    "Borough Park",
    "Brighton Beach",
    "Brooklyn Heights",
    "Brownsville",
    "Bushwick",
    "Canarsie",
    "Carroll Gardens",
    "Clinton Hill",
    "Cobble Hill",
    "Columbia St",
    "Coney Island",
    "Crown Heights",
    "Cypress Hills",
    "Downtown Brooklyn",
    "DUMBO",
    "Dyker Heights",
    "East Flatbush",
    "East New York",
    "Flatbush",
    "Flatlands",
    "Fort Greene",
    "Fort Hamilton",
    "Gerritsen Beach",
    "Gowanus",
    "Gravesend",
    "Greenpoint",
    "Kensington",
    "Manhattan Beach",
    "Midwood",
    "Mill Basin",
    "Navy Yard",
    "Park Slope",
    "Prospect Heights",
    "Prospect-Lefferts Gardens",
    "Red Hook",
    "Sea Gate",
    "Sheepshead Bay",
    "South Slope",
    "Sunset Park",
    "Vinegar Hill",
    "Williamsburg",
    "Windsor Terrace",
    "Battery Park City",
    "Chelsea",
    "Chinatown",
    "Civic Center",
    "East Harlem",
    "East Village",
    "Financial District",
    "Flatiron District",
    "Gramercy",
    "Greenwich Village",
    "Harlem",
    "Hell's Kitchen",
    "Inwood",
    "Kips Bay",
    "Little Italy",
    "Lower East Side",
    "Marble Hill",
    "Midtown",
    "Morningside Heights",
    "Murray Hill",
    "NoHo",
    "Nolita",
    "Roosevelt Island",
    "SoHo",
    "Stuyvesant Town",
    "Theater District",
    "Tribeca",
    "Two Bridges",
    "Upper East Side",
    "Upper West Side",
    "Washington Heights",
    "West Village",
    "Arverne",
    "Astoria",
    "Bayside",
    "Bayswater",
    "Bay Terrace",
    "Belle Harbor",
    "Bellerose",
    "Breezy Point",
    "Briarwood",
    "Cambria Heights",
    "College Point",
    "Corona",
    "Ditmars Steinway",
    "Douglaston",
    "East Elmhurst",
    "Edgemere",
    "Elmhurst",
    "Far Rockaway",
    "Flushing",
    "Forest Hills",
    "Fresh Meadows",
    "Glendale",
    "Glen Oaks",
    "Hollis",
    "Hollis Hills",
    "Holliswood",
    "Howard Beach",
    "Jackson Heights",
    "Jamaica",
    "Jamaica Estates",
    "Jamaica Hills",
    "Kew Gardens",
    "Kew Gardens Hills",
    "Laurelton",
    "Little Neck",
    "Long Island City",
    "Maspeth",
    "Middle Village",
    "Neponsit",
    "Ozone Park",
    "Queens Village",
    "Rego Park",
    "Richmond Hill",
    "Ridgewood",
    "Rockaway Beach",
    "Rosedale",
    "South Ozone Park",
    "Springfield Gardens",
    "St. Albans",
    "Sunnyside",
    "Whitestone",
    "Woodhaven",
    "Woodside",
    "Arden Heights",
    "Arrochar",
    "Bay Terrace, Staten Island",
    "Bloomfield",
    "Bull's Head",
    "Castleton Corners",
    "Charleston",
    "Chelsea, Staten Island",
    "Clifton",
    "Concord",
    "Dongan Hills",
    "Eltingville",
    "Emerson Hill",
    "Fort Wadsworth",
    "Graniteville",
    "Grant City",
    "Great Kills",
    "Grymes Hill",
    "Howland Hook",
    "Huguenot",
    "Lighthouse Hill",
    "Mariners Harbor",
    "Midland Beach",
    "New Brighton",
    "New Dorp",
    "New Dorp Beach",
    "New Springville",
    "Oakwood",
    "Pleasant Plains",
    "Port Ivory",
    "Port Richmond",
    "Prince's Bay",
    "Randall Manor",
    "Richmondtown",
    "Rosebank",
    "Rossville",
    "Shore Acres",
    "Silver Lake",
    "South Beach",
    "Stapleton",
    "St. George",
    "Todt Hill",
    "Tompkinsville",
    "Tottenville",
    "West Brighton",
    "Westerleigh",
    "Willowbrook",
    "Woodrow"
]