export const neighborhoodsList = [
    'Churchtown',
    'Kilmainham',
    'Stoneybatter/Arbour Hill',
    'Beaumont',
    'Mountjoy',
    'The Liberties',
    'North City Central/O\'Connell Street',
    'Lucan',
    'Drumcondra',
    'Cabra',
    'Dundrum',
    'Blackrock',
    'Crumlin',
    'Portobello',
    'Rialto',
    'Ranelagh and Rathmines',
    'Grafton Street/St. Stephens Green',
    'Santry',
    'Temple Bar',
    'Booterstown',
    'Docklands',
    'Dún Laoghaire',
    'Ballsbridge',
    'Phibsborough',
    'Rush',
    'North Strand',
    'Clontarf',
    'Rathgar',
    'Donnybrook',
    'Terenure',
    'Sandymount',
    'Ballybough',
    'Georgian Quarter',
    'Castleknock',
    'Kimmage',
    'Ranelagh',
    'Old City',
    'Cabra West',
    'Saggart',
    'Grand Canal Dock',
    'Raheny',
    'Finglas',
    'Trinity College',
    'Inchicore',
    'Smithfield',
    'East Wall',
    'Phoenix Park and Surrounds',
    'Monkstown',
    'Artane',
    'Rathfarnham',
    'Harold\'s Cross',
    'Dalkey',
    'Bonnybrook/Darndale',
    'Glasnevin',
    'Ballyfermot',
    'Scalpwilliam',
    'Ringsend/Irishtown',
    'Blanchardstown',
    'French Riviera',
    'Ballinteer',
    'Fairview',
    'Rathmines',
    'North City',
    'Churchtown Lower',
    'Sandyford',
    'Dangan',
    'Donaghmede',
    'Courtlands',
    'Saint Catherine\'s',
    'Northside',
    'Saint James\' (part of Phoenix Park)',
    'North Dock',
    'Clondalkin',
    'Brideswell Commons',
    'Poppintree',
    'Rathballylong',
    'Parknacross',
    'Clonsilla',
    'Carpenterstown',
    'Donnycarney',
    'Stillorgan',
    'Pelletstown',
    'Hansfield',
    'Walkinstown',
    'Grace Park',
    'Glasthule',
    'Merchants Quay',
    'Moneyatta Commons',
    'Deansgrange',
    'Arran Quay',
    'Saint Peter\'s',
    'Ashtown',
    'Margaretstown',
    'Castleknock (part of Phoenix Park)',
    'Dublin Docklands',
    'Cabra East',
    'Clontarf West',
    'Rotunda',
    'Glenageary',
    'Townparks',
    'Malahide',
    'Finnstown',
    'Quarry',
    'Shanganagh',
    'Bushwick',
    'Castaheany',
    'Porterstown',
    'Botanic',
    'Rathcoole',
    'Lissenhall Great',
    'Kilbogget',
    'Forestfields',
    'Fulham',
    'Balgriffin Park',
    'Clontarf East',
    'Holmpatrick',
    'Robswalls',
    'Doddsborough',
    'Fortunestown',
    'Churchtown Upper',
    'Merrion',
    'Kill of the Grange',
    'Saint Kevin\'s',
    'Usher\'s Quay',
    'Balgaddy',
    'Trimblestown',
    'Burrow',
    'Ballymadrough',
    'Greatcommon',
    'Ballymun',
    'Maynetown',
    'Newtown Little',
    'Corduff',
    'Beaverstown',
    'Cornelscourt',
    'Friarland',
    'Castlekelly',
    'Glebe',
    'Commons West',
    'Barnageera',
    'Ballyowen',
    'Rathmichael',
    'Baldoyle',
    'Whitehall',
    'Stapolin',
    'Woodpark',
    'Ballalease West',
    'Whitestown',
    'Rochestown',
    'Drumnigh',
    'Cookstown',
    'Lough Common',
    'Usher\'s Island',
    'Ballycullen',
    'Kilbarrack Lower',
    'Deanestown',
    'Tyrrelstown',
    'Leas',
    'Abbotstown',
    'Oldcourt',
    'Redcow',
    'Kilmacud',
    'Windy Arbour',
    'Mabestown',
    'Ardilea',
    'Yellow Walls',
    'Dublin',
    'Balgriffin',
    'Perrystown',
    'Carrickhill',
    'Rowlagh',
    'Kilgobbin',
    'Adamstown',
    'Priorswood',
    'Meakstown',
    'Santry Demesne',
    'Mount Merrion',
    'Stillorgan Park',
    'Murphystown',
    'Schollarstown',
    'Parslickstown',
    'Newpark',
    'Ballydowd',
    'Dubber',
    'Mountmerrion',
    'Rathingle',
    'West Los Angeles',
    'Brackenstown',
    'Tootenhill',
    'Crooksling',
    'Kilnamanagh',
    'Brenanstown',
    'Ballygillane Big',
    'Finglas South',
    'Cruiserath',
    'Hartstown',
    'Cherry Orchard',
    'Kiltipper',
    'Montpelier',
    'Hollywoodrath',
    'Rush Demesne',
    'Farranboley',
    'Oldbawn',
    'Cooldown Commons',
    'Portmarnock',
    'Kilmore',
    'Killiney',
    'Falcarragh',
    'Racecourse Common',
    'Wood Quay',
    'Johnstown',
    'Kilmahuddrick',
    'Scholarstown',
    'Knocklyon',
    'Windmill Lands',
    'Nevinstown West',
    'Elm park, merrion road',
    'Roebuck',
    'Thomastown',
    'Kilcarbery',
    'Redcowfarm',
    'Hollystown',
    'Lusk',
    'Cloonmonad',
    'Templeogue',
    'Richardstown',
    'Ballalease North',
    'Ballygall',
    'Farney Park',
    'Ballycragh',
    'Marino',
    'Honeypark',
    'Coldwinters',
    'Killeen',
    'Dublin 1',
    'Stradbrook',
    'Saint James',
    'Stoneybatter',
    'Ballinleague',
    'Raheny - Greendale',
    'Bullock',
    'Phoenix Park racecourse',
    'Oldtown',
    'Newtown Blackrock',
    'Cabinteely',
    'Bohernabreena',
    'Regles',
    'Howth',
    'Hilltown',
    'Piercetown',
    'Williamstown',
    'North Wall',
    'Cappoge',
    'Rathmines Great',
    'Ballyboden',
    'Raheny - St. Assam',
    'Laughanstown',
    'Swords Demesne',
    'Kinsealy',
    'Barnageeragh',
    'Buzzardstown',
    'Esker South',
    'Tobermaclugg',
    'Bremore',
    'Sheepmoor',
    'Charlestown',
    'Hackettsland',
    'Grange',
    'Seapoint Or Templehill',
    'Trimleston Or Owenstown',
    'Finglas North',
    'Outlands',
    'Stillorgan Grove',
    'Belcamp',
    'Jordanstown',
    'Raheny - Foxfield',
    'Gibbons',
    'Kingswood',
    'South Central Houston',
    'Caulstown',
    'Clonee',
    'Deansrath',
    'Mooretown',
    'Fosterstown North',
    'Tipperstown',
    'Drinan',
    'Woodside',
    'Lansville',
    'Ronanstown',
    'Dublin 4',
    'Dooroge',
    'Clifden',
    'Glasthule Village',
    'Bray',
    'Castle Street',
    'Dublin 3',
    'Dublin 7',
    'Templeogue Village',
    'Brownsbarn',
    'Clonshagh',
    'Lower',
    'Bethnal Green',
    'Ballybrack',
    'Phibsboro',
    'Mulgannon',
    'Swords',
    'Cappagh',
    'Canasvieiras',
    'Laraghcon',
    'Gortamullin',
    'Kiltalown',
    'Newcastle South',
    'Dublin 8',
    'Drummartin',
    'Corballis',
    'Rathbeal',
    'Apt 34',
    'Hansfield Or Phibblestown',
    'Glenamuck North',
    'Woodtown',
    'Leastown',
    'Barrysparks',
    'Bonamoussadi',
    'Jullouville-les-Pins',
    'Quaid Block',
    'Belmayne',
    'Tatranská Polianka',
    'Shankill',
    'Carrickmines Great',
    'Kilmartin',
    'Drimnagh',
    'Ringsend',
    'Clongriffin',
    'Drummond Etra',
    'Rahillion',
    'Jobstown',
    'Tyburnia',
    'Sutton',
    'Chácaras Mogiano',
    'st Margaret\'s road',
    'Rathborne',
    'Rathmines Little',
  ];